name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write  # Required for PyPI trusted publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Upgrade pip and install build
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build sdist and wheel
        run: python -m build
      - name: Publish to PyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          packages-dir: dist
          # To use API token instead of OIDC, set PYPI_API_TOKEN secret and uncomment:
          # password: ${{ secrets.PYPI_API_TOKEN }}

