name: Tests

on:
  push:
  pull_request:

jobs:
  lint:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install Ruff and Mypy
        run: pip install ruff==0.11.7 mypy
      - name: Ruff check
        run: ruff check .
      - name: Ruff format check
        run: ruff format --check .
      - name: Mypy type check
        run: mypy admin_auto_filters

  test:
    name: Python ${{ matrix.python-version }} - Django ${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        django: ["4.2", "5.0", "5.1", "5.2"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Django
        run: pip install "Django~=${{ matrix.django }}.0"
      - name: Run tests
        run: python ./tests_manage.py test tests -v 2
